// <auto-generated />
using Dot.Kitchen.Ons.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Dot.Kitchen.Ons.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171125205444_UpdateColumnName")]
    partial class UpdateColumnName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dot.Kitchen.Ons.Domain.Scrape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("FinishedAt");

                    b.Property<int>("NumberOfRecordsScraped")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("SourceId");

                    b.Property<DateTime>("StartedAt");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasName("PK_Scrapes");

                    b.HasIndex("SourceId");

                    b.ToTable("Scrapes");
                });

            modelBuilder.Entity("Dot.Kitchen.Ons.Domain.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasName("PK_Sources");

                    b.HasAlternateKey("Name");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Dot.Kitchen.Ons.Domain.Scrape", b =>
                {
                    b.HasOne("Dot.Kitchen.Ons.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
